### ISSUE TITLE
OpenShell start menu bugs

### ISSUE THREAD

**Issue by SIX10** [dremin/RetroBar#159]
Ever since the multiple displays update, RetroBar has had some issues with OpenShell's start menu. Usually it works, but as time goes on clicking the start button places the start menu in strange places, or not at all. Simply restarting RetroBar fixes this, but it's an annoyance when trying to shut down the PC and I can't open the start menu. This issue was not present in previous versions.

**Comment by dremin** [comment]
Odd, but I have a suspicion-- if you click on a notification area icon first, before clicking the start button, does it always open in the correct spot?

**Comment by erectus86** [comment]
When I'm just on the desktop and open the start menu (modified with OpenShell), it just shows up at the top left corner of my screen. But only when I'm on the desktop, so if I have another app open, let's say Chrome, the start menu works fine.

**Comment by SIX10** [comment]
> Odd, but I have a suspicion-- if you click on a notification area icon first, on the same display as the start button, before clicking the start button, does it always open in the correct spot?

I'll try that, but I have noticed apps that are opened from the notification area (such as the sound bar) also experience the same problem as the start menu. Right now it's only the notification area apps appearing in strange places, usually at the top of the screen, I can still open and use them just fine.

**Comment by alien2003** [comment]
Confirmed on Windows 10 2004 AME.

If there is no any window opened at the moment, Open-Shell start menu does not appear at all. If at least one window is opened, Start Menu appears as expected

**Comment by dremin** [comment]
I think I have a fix for this. [Here's a test build with the fix](https://github.com/dremin/RetroBar/suites/4436262185/artifacts/117527775) (GitHub login is required). If some of you could confirm the fix works, I'd appreciate it!

**Comment by dremin** [comment]
This is fixed in the latest release.

**Comment by RastyBasic** [comment]
Same bug appeared again in latest version 1.15
Using two monitors and "Show on multiple displays" feature
OS:  Windows 11 23H2

Fast fix is unlock and lock taskbar

**Comment by NotRollo** [comment]
Issue still occurring on 1.16, also with "Show on multiple displays" enabled.
Windows 11 23H2

Unlocking and locking the taskbar does not fix this issue for me.

**Comment by syheliel** [comment]
I can reproduce this error in WIN 11 24H2. The ad-hoc solution is pressing `Win` button.

**Comment by masonamadeus** [comment]
Same issue on Win11 24H2 with current latest OpenShell (4.4.196) and latest Retrobar (1.20.37).

No change when locking/unlocking the taskbar, or toggling "show on multiple displays". I also tried toggling any options I could think of in various combinations with both apps (as some suggestions indicated to change "Align start menu to working area" etc) but to no avail.

Openshell works flawlessly when retrobar is closed, but when retrobar is running the start button will summon the Win11 menu no matter what. In my case, even pressing the Win key doesn't work. I haven't yet stumbled on a setting that makes a difference.

Real bummer because I love both of these apps a lot! They used to work perfectly in concert with one another.

**Comment by dremin** [comment]
> Same issue on Win11 24H2 with current latest OpenShell (4.4.196) and latest Retrobar (1.20.37).
> 
> No change when locking/unlocking the taskbar, or toggling "show on multiple displays". I also tried toggling any options I could think of in various combinations with both apps (as some suggestions indicated to change "Align start menu to working area" etc) but to no avail.
> 
> Openshell works flawlessly when retrobar is closed, but when retrobar is running the start button will summon the Win11 menu no matter what. In my case, even pressing the Win key doesn't work. I haven't yet stumbled on a setting that makes a difference.
> 
> Real bummer because I love both of these apps a lot! They used to work perfectly in concert with one another.

I believe you may be experiencing a different issue than the original one. If Open Shell Menu is not opening at all for the Win key, in the Open Shell Menu settings, make sure you set Controls > Windows Key opens > Open-Shell Menu. This should also cause it to open as expected with RetroBar.

**Comment by masonamadeus** [comment]
> I believe you may be experiencing a different issue than the original one. If Open Shell Menu is not opening at all for the Win key, in the Open Shell Menu settings, make sure you set Controls > Windows Key opens > Open-Shell Menu. This should also cause it to open as expected with RetroBar.

Oops, my bad for not mentioning -- I had already turned that setting on, and it was still not working. Even tried several reinstalls of both apps, resetting settings, etc.

Just in case this info is useful: I uninstalled Retrobar and installed Stardock Start11 - and a very similar problem happens! The Win key will only summon the default windows menu and not the modified one. Unlike Retrobar though, when I mouseclick the start button it summons the modified menu as expected. Weird.

This makes me think it might be something specific to my machine... though I'm at a total loss for what it would be lol.

Thanks for your reply, and for making Retrobar! It's very cool, even if I'm having trouble with my convoluted setup.

**Comment by dremin** [comment]
> > I believe you may be experiencing a different issue than the original one. If Open Shell Menu is not opening at all for the Win key, in the Open Shell Menu settings, make sure you set Controls > Windows Key opens > Open-Shell Menu. This should also cause it to open as expected with RetroBar.
> 
> Oops, my bad for not mentioning -- I had already turned that setting on, and it was still not working. Even tried several reinstalls of both apps, resetting settings, etc.
> 
> Just in case this info is useful: I uninstalled Retrobar and installed Stardock Start11 - and a very similar problem happens! The Win key will only summon the default windows menu and not the modified one. Unlike Retrobar though, when I mouseclick the start button it summons the modified menu as expected. Weird.
> 
> This makes me think it might be something specific to my machine... though I'm at a total loss for what it would be lol.
> 
> Thanks for your reply, and for making Retrobar! It's very cool, even if I'm having trouble with my convoluted setup.

Interesting! It is possible another application is affecting the Windows key.
