### ISSUE TITLE
Authenticity of the Windows XP Blue theme is not 100%

### ISSUE THREAD

**Issue by tomrow** [dremin/RetroBar#185]
The spinner button used when taskbar buttons trail off the allotted area appears to use incorrect graphics, and the sliding animation for collapsing and expanding the system tray is missing.

![image](https://user-images.githubusercontent.com/10169982/144748965-9b3fd876-c1a5-479d-9c8d-36f00f75bf1e.png)
Windows XP

![image](https://user-images.githubusercontent.com/10169982/144748978-eaf0b05f-b006-4e1c-9a96-6f458816db49.png)
RetroBar

**Comment by tomrow** [comment]
A strange dotted border surrounds the Start button after the Start Menu has been dismissed.
![image](https://user-images.githubusercontent.com/10169982/144749077-9320c0c2-1750-45a1-a4b3-2d7c593879a7.png)

**Comment by xoascf** [comment]
I think I can fix the first issue rq.

**Comment by Alvyssy** [comment]
How do you make those buttons appear in the first place? Also when I right click on the audio icon the old mixer appears only if I restart explorer which messes up the padding of the windows

**Comment by tomrow** [comment]
The Up-Down spinner appears when there are so many applications open that there is no longer room for them in the taskbar. As for the volume control, I can't get the context menu to appear at all in retrobar, so I have to navigate to Settings via the Start Menu to change device options

**Comment by dremin** [comment]
This is fixed in the latest release.

**Comment by Alvyssy** [comment]
@dremin the volume context menu still doesn't work for me, I get it working by restarting explorer.exe but it messes up the windows sizes
