### ISSUE TITLE
Thin gap between taskbar and start menu-volume window

### ISSUE THREAD

**Issue by mrt505** [dremin/RetroBar#193]
When i click start, speaker etc. button in taskbar, windows in first 2-3 seconds looks like this. And thin black line still appears in sometimes(like after minimized and maximized window) in chromium based Brave browser.    
![1](https://user-images.githubusercontent.com/89605569/146821643-b74e1457-6898-4c98-86ce-ff39b7ca885d.png)
![2](https://user-images.githubusercontent.com/89605569/146821645-ddcd823f-b554-48e9-9a2e-3eec94c2c6ec.png)

**Comment by mrt505** [comment]
This is after fullscreen video in Youtube. Annoying black line still appears. It became normal after i minimize and maximize the window.
![Ekran Alıntısı](https://user-images.githubusercontent.com/89605569/147713176-811a2c00-6c1d-4d01-bd99-9eea22266c15.PNG)

**Comment by mrt505** [comment]
@dremin 
will you fix this issue in next release? because it is so annoying and makes unusable.

**Comment by dremin** [comment]
I believe the maximized windows issue should now be fixed in [this test build](https://github.com/dremin/RetroBar/suites/5272119818/artifacts/162979122) (link requires GitHub login). Would you be able to verify if that version works correctly for you?

**Comment by mrt505** [comment]
> I believe the maximized windows issue should now be fixed in [this test build](https://github.com/dremin/RetroBar/suites/5272119818/artifacts/162979122) (link requires GitHub login). Would you be able to verify if that version works correctly for you?

looks like there isn't problem with minimize and maximize. but it is still appears after exit fullscreen videos in youtube.

**Comment by mrt505** [comment]
@xoascf @dremin any new about this critical bug? i think this bug's reason same with  #258 and #234

**Comment by mrt505** [comment]
> This is after fullscreen video in Youtube. Annoying black line at top of the taskbar still appears. It becames normal after i minimize and maximize the window. ![Ekran Alıntısı](https://user-images.githubusercontent.com/89605569/147713176-811a2c00-6c1d-4d01-bd99-9eea22266c15.PNG)

@dremin do you have any plans to fix this bug in the next release? this black line is very annoying. i reported this bug to you almost 1 year ago and i can't use retrobar because of this bug.
